version: '3.9'

services:
  app:
    build: 
      context: .
    ports:
      - "8001:8001"
    volumes:
      - ./api:/api
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
      